name: photon PLATFORM
motto: "**TOOLS**\r\n\r\n**TO SHINE YOUR**\r\n\r\n**LIGHT**"
contact: this is a phi ARCHITECT project
facebook: phiarchitect
twitter: phi_architect
linkedin: phiarchitect
github: photon-platform
youtube: UCYzRQS16EBmsbKuyKMFHSFQ
owa:
  siteId: 85a952d89d952fb38459f0aca0de1c03
  trackPageView: true
  trackCLicks: false
  trackDomStream: false
google_search: 
