name: photon PLATFORM
motto: "**TOOLS**\r\n\r\n**TO SHINE YOUR**\r\n\r\n**LIGHT**"
contact: this is a phi ARCHITECT project
facebook: phi.architect
twitter: phi_architect
linkedin: iamphi
youtube: UCYzRQS16EBmsbKuyKMFHSFQ
github: photon-platform
owa:
  siteId: 85a952d89d952fb38459f0aca0de1c03
  trackPageView: true
  trackCLicks: false
  trackDomStream: false
google_search: bYQ6W9XS6CPkwqqn-S3jJUoVhwgwF7U6YHQrWQlkwgE
