title: photon PLATFORM
default_lang: en
author:
  name: phi
  email: phi@illumiphi.com
taxonomies:
  - category
  - tag
  - photon
metadata:
  description: 'complete platform for developing, publishing, and managing content in the digital world'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
logo: photon-logo.png

