color:
  key:
    hue: 44
  1:
    hueOffset: 120
  2:
    hueOffset: -150
  saturation: 33
  lightness:
    lighter: 90
    light: 75
    mid: 44
    dark: 33
    darker: 19
  foreground: '#333'
  background: '#EFEFEF'
font: Lato
font_display: Montserrat
font_code: monospace
header_height: 9em
fitz: .5em
col: 18em
